module.exports = {
  n: 2,
  title: 'REVIEW OF LITERATURE',
  blocks: [
    { h2: '2.1 Literature Survey' },
    { p: '**Survey strategy.** The literature survey was carried out in three steps. First, the KJS-AGR-01 use-case document {cite:usecase} was analysed to extract the required AI models, data sources and governance requirements. Second, peer-reviewed literature was searched on IEEE Xplore, ScienceDirect, MDPI and Google Scholar using combinations of the keywords *smart irrigation*, *irrigation scheduling*, *sugarcane water requirement*, *crop evapotranspiration*, *soil moisture remote sensing*, *machine learning in agriculture*, *yield prediction*, *decision support system* and *explainable AI*. Foundational standards were taken directly from the Food and Agriculture Organization (FAO) irrigation and drainage papers. Third, works were selected if they (i) proposed a method or system for irrigation or crop decision support, (ii) provided an algorithm or dataset used in this project, or (iii) defined an evaluation, scheduling or governance principle that the project follows. The selected works were grouped into the five themes shown in {fig:taxonomy} and are summarised in text below and in tabular form in {tab:lit}.' },
    { fig: 'uml_taxonomy.png', id: 'taxonomy', caption: 'Taxonomy of the reviewed literature', width: 4.6, maxH: 6.6 },

    { h3: '2.1.1 Agronomic and physical models of crop water use' },
    { p: 'The FAO Irrigation and Drainage Paper 56 by Allen et al. {cite:allen1998} is the international reference for computing crop water requirements. It defines the reference evapotranspiration (ET_{0}), crop coefficients (K_{c}) that vary with growth stage, and a root-zone soil-water balance in which total available water (TAW), readily available water (RAW) and a water-stress coefficient (K_{s}) determine when irrigation is needed. Because full Penman–Monteith inputs are rarely available at plot level, Hargreaves and Samani {cite:hargreaves1985} proposed a temperature-based ET_{0} equation that requires only temperature and extraterrestrial radiation; it is widely used where weather stations are sparse. The consequences of water deficit on production are captured by the FAO-33 yield-response relationship of Doorenbos and Kassam {cite:doorenbos1979}, which links the relative yield decrease to the relative evapotranspiration deficit through a yield-response factor K_{y} (about 1.2 for sugarcane). For sugarcane specifically, Inman-Bamber and Smith {cite:inman2005} reviewed how water deficits reduce canopy expansion and stalk elongation, showing that sensitivity is highest during the active growth phases. FAO also summarises the seasonal water needs and growth stages of the crop {cite:fao_sugarcane}. These models provide a sound scientific basis for scheduling but are deterministic, require complete inputs, and do not learn from data or express uncertainty.' },

    { h3: '2.1.2 IoT sensor-based smart irrigation' },
    { p: 'Goap et al. {cite:goap2018} built an IoT-based smart irrigation system that combines soil-moisture, temperature and humidity sensors with weather-forecast data, and uses machine learning to predict soil moisture and automate irrigation. The work showed that forecasts can prevent unnecessary irrigation, but the approach requires sensors in every field and was demonstrated at the scale of a single field. Kamienski et al. {cite:kamienski2019} described SWAMP, an IoT-based smart water management platform for precision irrigation evaluated in pilots with different crops and countries; the emphasis was on a configurable platform architecture rather than on crop-specific predictive models or farmer-facing advisories. Both works confirm the value of connected data, while highlighting the cost of dense sensor networks when thousands of smallholder plots must be covered — precisely the situation of the GBL/KIAAR network.' },

    { h3: '2.1.3 Remote sensing and geospatial data' },
    { p: 'Remote sensing offers plot-level observations without in-field hardware. The Normalized Difference Vegetation Index (NDVI), introduced by Rouse et al. {cite:rouse1974}, remains the most widely used indicator of green biomass and crop vigour. Satellite missions such as SMAP {cite:entekhabi2010} provide regular soil-moisture observations, although at coarse resolution and only for the surface layer, so the root-zone water state must be modelled. Cloud platforms such as Google Earth Engine {cite:gorelick2017} make it possible to extract such indices for thousands of plots, and global land-cover products such as ESA WorldCover {cite:zanaga2021} are used to locate cropland; the dataset of this project was sampled on the WorldCover cropland class. Remote sensing therefore supplies the *inputs* for large-scale advisory, but by itself does not produce irrigation decisions.' },

    { h3: '2.1.4 Machine learning in agriculture' },
    { p: 'Liakos et al. {cite:liakos2018} reviewed machine learning in agriculture across crop, livestock, water and soil management, and Jha et al. {cite:jha2019} surveyed AI-based automation, including irrigation. Both reviews report wide use of ML for individual prediction tasks, but few systems integrate several predictions into a single operational advisory. In their systematic review of ML-based crop yield prediction, van Klompenburg et al. {cite:vanklompenburg2020} found that temperature, rainfall and soil type are the most frequently used features and that many algorithms perform competitively, yet yield prediction is usually studied in isolation from irrigation decisions. Regarding model choice, Random Forests {cite:breiman2001} and Gradient Boosting Machines {cite:friedman2001} are ensemble methods of decision trees that are accurate and robust on tabular data; Grinsztajn et al. {cite:grinsztajn2022} showed that tree-based models still outperform deep neural networks on typical medium-sized tabular datasets. Reliable implementations are available in scikit-learn {cite:pedregosa2011}, and standard evaluation methodology is described by Hastie et al. {cite:hastie2009}. When labelled data are scarce, Karpatne et al. {cite:karpatne2017} argue for *theory-guided data science*, in which scientific knowledge constrains or generates the training data — the principle adopted by SMA. For trust and accountability, Lundberg and Lee {cite:lundberg2017} proposed SHAP explanations; SMA uses a lighter, model-agnostic sensitivity explanation that can run for every request.' },

    { h3: '2.1.5 Decision support, scheduling and governance' },
    { p: 'Navarro-Hellín et al. {cite:navarro2016} developed a smart irrigation decision support system that uses soil and climate sensor data with machine-learning regression to estimate weekly irrigation needs, reproducing expert decisions closely; however, the approach depends on an expert-labelled irrigation history. Allocation of pumping time under limited electricity is a scheduling problem: Smith\'s rule {cite:smith1956} (Weighted Shortest Processing Time, WSPT) is optimal for minimising total weighted completion time on a single machine, and list-scheduling heuristics for parallel machines are well established {cite:pinedo2016}. For data quality, the modified z-score of Iglewicz and Hoaglin {cite:iglewicz1993} gives a robust rule for flagging outliers, and K-means clustering {cite:macqueen1967} is a standard way of grouping observations into zones. Finally, the Digital Personal Data Protection Act, 2023 {cite:dpdp2023} sets the legal requirements of consent, purpose limitation and data minimisation that any farmer-data platform in India must follow, and the COCOMO model of Boehm {cite:boehm1981} is the classical basis for estimating software development effort.' },

    { p: '{tab:lit} summarises every reference used in this report, including the approach, the key contribution and the limitation relevant to this project.' },
    { table: { fromReferences: true, headers: ['Ref.', 'Authors / Year', 'Approach', 'Key contribution / finding', 'Limitation w.r.t. this project'], rows: [], widths: [7, 16, 27, 25, 25], size: 9.5 }, id: 'lit', caption: 'Summary of the literature survey' },

    { h2: '2.2 Research Gaps' },
    { p: 'From the survey, the following research gaps were identified for a large-scale sugarcane irrigation advisory such as the one required by KIAAR and GBL:' },
    { numbered: [
      '**No integrated, multi-model advisory.** Existing works predict soil moisture, irrigation need or yield separately; very few combine irrigation timing, duration, water stress, yield loss from delay, fertigation and disease risk into one consistent recommendation {cite:liakos2018,vanklompenburg2020}.',
      '**Dependence on dense sensors or labelled history.** IoT systems {cite:goap2018,kamienski2019} need hardware in every field, and ML decision-support systems {cite:navarro2016} need expert-labelled irrigation logs — neither is available for thousands of smallholder plots today.',
      '**Deterministic agronomic models without uncertainty.** FAO-based schedulers {cite:allen1998} give a single answer and cannot express confidence or learn from field feedback.',
      '**Weather-blind schedules.** Fixed-interval irrigation ignores forecast rain, and few systems quantify the water saved by postponing irrigation.',
      '**Energy constraints ignored.** Rural pump sets receive three-phase power only in limited windows, but irrigation advice is rarely coupled with pump scheduling {cite:smith1956,pinedo2016}.',
      '**Limited explainability and farmer accessibility.** Many systems present technical outputs in English only, without explanations, voice output or local-language support, which limits farmer trust and adoption {cite:jha2019}.',
      '**Governance.** Privacy, human oversight and continuous learning from farmer feedback are rarely designed into prototype systems {cite:dpdp2023}.',
    ] },
    { p: '{tab:gaps} maps each gap to the way it is addressed in SMA.' },
    { table: { headers: ['Research gap', 'How SMA addresses it'], widths: [38, 62], rows: [
      ['Isolated single-task models', 'Seven coordinated models (next irrigation, water requirement, depth, stress, yield, yield loss, disease risk) plus K-Means zones feed one decision engine and one advisory.'],
      ['Need for sensors / labelled history', 'Physics-informed labels from FAO-56 and FAO-33 on 12,000 seasonal scenarios; the same pipeline retrains on real labels when they become available.'],
      ['No uncertainty in agronomic models', 'Random-Forest tree spread gives ± days; class probabilities are shown instead of single labels.'],
      ['Weather-blind schedules', 'Forecast rain is a model input; a "no-rain" counterfactual converts advice into "skip" and quantifies rain used.'],
      ['Energy constraints ignored', 'WSPT pump scheduler within power windows and feeder capacity, compared with a first-come rotation.'],
      ['Low explainability / accessibility', 'Per-feature explanations, 14-day moisture projection, advisories in English, Kannada, Hindi and Marathi, read-aloud and chatbot.'],
      ['Weak governance', 'Anonymised plot IDs, input validation, accept/override feedback log for retraining, documented limitations.'],
    ] }, id: 'gaps', caption: 'Research gaps and how SMA addresses them' },
  ],
};
