module.exports = {
  n: 3,
  title: 'REQUIREMENT SPECIFICATION',
  blocks: [
    { h2: '3.1 Introduction' },
    { p: 'This chapter specifies what the Smart Moisture Advisor must do and what it needs in order to do it. The requirements were derived from the KJS-AGR-01 use case {cite:usecase}, from discussions of the expected users (farmers, field supervisors, agronomists, sugar-factory cane departments and data scientists) and from the constraints of the provided dataset. The hardware and software requirements are listed separately for development, for the application server and for end-user devices. The chapter then states the functional and non-functional requirements, assesses technical, economic, operational, schedule and legal feasibility, estimates the cost of the project with the COCOMO model {cite:boehm1981} and presents the project schedule.' },
    { p: 'A guiding decision was to keep the deployed system **light and offline-capable**: models are trained once in Python and exported as JSON, so the application needs only Node.js and a browser and can run on an ordinary office laptop.' },

    { h2: '3.2 Hardware requirements' },
    { p: 'The hardware requirements for development and model training are given in {tab:hwdev}. Training takes about 75 seconds on a four-core CPU; no GPU is required.' },
    { table: { headers: ['Component', 'Minimum', 'Used / recommended'], widths: [26, 34, 40], rows: [
      ['Processor', 'Dual-core x86-64, 2.0 GHz', 'Quad-core x86-64 (4 vCPU)'],
      ['Memory (RAM)', '4 GB', '8–16 GB'],
      ['Storage', '2 GB free (code, dependencies, models)', '10 GB SSD'],
      ['Network', 'Needed only to install packages', 'Broadband for map tiles and updates'],
    ] }, id: 'hwdev', caption: 'Hardware requirements for development and model training' },
    { p: 'The application server hosts the Node.js API and the static web application. Because inference for all 1,000 plots completes in about 0.2 seconds, a small machine is sufficient ({tab:hwsrv}). End users only need a device with a modern web browser.' },
    { table: { headers: ['Tier', 'Specification', 'Purpose'], widths: [22, 40, 38], rows: [
      ['Application server', '2 vCPU, 2–4 GB RAM, 5 GB disk (laptop, office PC or cloud VM)', 'Runs Node.js API, model inference, scheduler and serves the web app'],
      ['Supervisor / office client', 'PC or laptop with a modern browser, 4 GB RAM', 'Dashboard, farm map, pump scheduler, model insights'],
      ['Farmer / field-staff client', 'Android smartphone (2 GB RAM) with Chrome, or feature phone for SMS', 'Plot advisory, chatbot, read-aloud; SMS text for basic phones'],
    ] }, id: 'hwsrv', caption: 'Hardware requirements for deployment' },

    { h2: '3.3 Software requirements' },
    { p: 'All software is free and open-source and runs on Windows, Linux and macOS; the requirements are listed in {tab:sw}. PlantUML, Graphviz and Matplotlib were used for diagrams, and Git/GitHub for version control.' },
    { table: { headers: ['Category', 'Software / library', 'Version', 'Role in SMA'], widths: [18, 28, 14, 40], rows: [
      ['Runtime', 'Node.js', '18 or newer (22 used)', 'Application server and ML inference {cite:nodejs}'],
      ['Web framework', 'Express', '5.x', 'REST API and static file server'],
      ['Data parsing', 'csv-parse', '7.x', 'Reading the plot dataset'],
      ['Visualisation', 'Chart.js, Leaflet', '4.x, 1.9', 'Charts and interactive farm map {cite:leaflet}'],
      ['ML training', 'Python, NumPy, pandas, scikit-learn', '3.9+, 2.x, 2.x, 1.3+', 'Label generation, training, evaluation, export {cite:pedregosa2011}'],
      ['Testing', 'node:test (built-in)', 'Node 18+', 'Unit, parity and API tests'],
    ] }, id: 'sw', caption: 'Software requirements' },

    { h2: '3.4 Feasibility Study' },
    { p: 'A feasibility study was carried out to confirm that the system can be built and used within the constraints of the project. The five dimensions considered are summarised below.' },
    { p: '**Technical feasibility.** The required data are in the dataset and can be refreshed from satellite platforms {cite:gorelick2017}; the missing labels are replaced by physics-informed labels from FAO-56 and FAO-33 {cite:allen1998,doorenbos1979,karpatne2017}; models train in about a minute and serve in milliseconds; and the stack is mature. The project is technically feasible.' },
    { p: '**Economic feasibility.** All software is open-source and the system runs on existing laptops or a small cloud virtual machine. The main costs are development effort and, for a field deployment, optional sensors and SMS charges. The potential benefits — about 38% less irrigation water under normal conditions (Chapter 7), lower pump electricity use and reduced yield loss — are recurring, so the system is economically attractive.' },
    { p: '**Operational feasibility.** Farmers receive short instructions such as "Start irrigating this morning: about 22 hours of pumping" in their own language, with voice output for low-literacy users. Supervisors use a familiar dashboard and map. Human-in-the-loop accept/override buttons keep experts in control, which supports adoption.' },
    { p: '**Schedule feasibility.** The work was divided into ten phases over one semester (Section 3.8). Using a light stack and pre-trained models allowed the complete system to be built, tested and documented within the available time.' },
    { p: '**Legal and ethical feasibility.** The dataset contains no personal data; plots are identified by anonymised IDs. Feedback logs store only plot ID, role and decision, in line with the data-minimisation principle of the DPDP Act, 2023 {cite:dpdp2023}.' },
    { h2: '3.5 Cost Estimation' },
    { p: 'The development effort was estimated with the basic COCOMO model {cite:boehm1981} for an *organic* project (small team, familiar environment, flexible requirements). The size of the delivered software, counted as non-blank lines of code, is shown in {tab:loc}.' },
    { table: { headers: ['Module', 'Language', 'Lines of code'], widths: [50, 25, 25], align: [0, 0, 2], rows: [
      ['Server: API, data loader, inference, decision engine, scheduler, chatbot', 'JavaScript', '1,332'],
      ['Web application: pages, charts, map, styles', 'JavaScript, HTML, CSS', '1,765'],
      ['ML pipeline: agronomy engine, training, export', 'Python', '474'],
      ['Automated tests', 'JavaScript', '158'],
      ['**Total**', '', '**3,729 (≈ 3.73 KLOC)**'],
    ] }, id: 'loc', caption: 'Size of the developed software' },
    { p: 'For an organic project the effort *E* (person-months), development time *D* (months) and average staffing *S* are given by:' },
    { eq: 'E = 2.4 × (KLOC)^{1.05} = 2.4 × (3.73)^{1.05} ≈ 9.56 person-months', id: 'cocomoE' },
    { eq: 'D = 2.5 × E^{0.38} = 2.5 × (9.56)^{0.38} ≈ 5.9 months', id: 'cocomoD' },
    { p: 'The average staffing E/D ≈ 1.6 persons over about six months matches a two-member team working part-time. The notional development cost and the indicative running cost of a deployment are given in {tab:cost}. Market rates are indicative and should be confirmed at the time of deployment.' },
    { table: { headers: ['Item', 'Basis', 'Estimated cost (₹)'], widths: [36, 40, 24], align: [0, 0, 2], rows: [
      ['Development effort (notional)', '9.56 person-months × ₹25,000 per person-month', '2,39,000'],
      ['Software licences', 'Open-source stack', '0'],
      ['Development hardware', 'Existing student laptops', '0'],
      ['Dataset', 'Provided with the use case', '0'],
      ['Application hosting (optional)', 'Small cloud VM, 2 vCPU / 4 GB, ≈ ₹1,500–3,000 per month', '18,000–36,000 per year'],
      ['SMS advisories (optional)', '1,000 plots × 2 SMS/week × 52 weeks at ≈ ₹0.20', '≈ 20,800 per year'],
      ['Field sensors (future pilot)', 'Soil-moisture nodes and gateway for a pilot village', 'To be quoted'],
    ] }, id: 'cost', caption: 'Cost estimation' },

    { h2: '3.6 Functional Requirements' },
    { p: 'The functional requirements define the services SMA must provide. They are listed in {tab:fr} with their priority.' },
    { table: { headers: ['ID', 'Requirement', 'Priority'], widths: [9, 76, 15], rows: [
      ['FR1', 'Load plot records (features, polygons) from CSV, impute missing NDVI and flag outliers.', 'High'],
      ['FR2', 'Predict days to next irrigation with uncertainty for every plot.', 'High'],
      ['FR3', 'Predict crop water requirement (ETc) and irrigation depth; convert to volume and pump hours for the chosen irrigation method and pump flow.', 'High'],
      ['FR4', 'Predict water-stress probabilities (None, Mild, Moderate, Severe) and disease/pest risk (Low, Medium, High).', 'High'],
      ['FR5', 'Predict yield and yield loss for irrigation delays of 0–14 days.', 'High'],
      ['FR6', 'Adjust advice for forecast rain and report irrigations that can be skipped.', 'High'],
      ['FR7', 'Generate a stage-wise fertigation plan (urea, 12-61-0, MOP) with soil-based notes.', 'Medium'],
      ['FR8', 'Optimise pump schedules within power windows and feeder capacity; compare with rotation.', 'High'],
      ['FR9', 'Generate advisories in English, Kannada, Hindi and Marathi, with read-aloud and SMS copy.', 'High'],
      ['FR10', 'Provide a chatbot that answers plot questions in the four languages.', 'Medium'],
      ['FR11', 'Show a region dashboard, a farm map with prediction layers and a what-if simulator.', 'High'],
      ['FR12', 'Explain each recommendation and show model accuracy, importance and confusion matrices.', 'Medium'],
      ['FR13', 'Record accept/override feedback for retraining.', 'Medium'],
      ['FR14', 'Retrain all models from data with one command and verify inference parity.', 'Medium'],
    ] }, id: 'fr', caption: 'Functional requirements' },

    { h2: '3.7 Non-Functional Requirements' },
    { table: { headers: ['Category', 'Requirement'], widths: [22, 78], rows: [
      ['Performance', 'Score all 1,000 plots in under 1 s; single-plot advisory in under 100 ms on a laptop.'],
      ['Accuracy', 'Each model must outperform its linear/logistic baseline on unseen plots.'],
      ['Scalability', 'Stateless API with per-scenario caching; linear scaling to 25,000 plots.'],
      ['Usability', 'Simple language, local languages, voice output, responsive layout for phones, light/dark themes.'],
      ['Accessibility', 'Colour-blind-safe chart palette; status shown with icons and labels, not colour alone.'],
      ['Security', 'Validate and clamp all inputs; no secrets in code; restrict request size.'],
      ['Privacy', 'Anonymised plot IDs; no personal data; minimal feedback log.'],
      ['Maintainability', 'Modular code, documented API, automated tests, reproducible training; runs offline on Windows, Linux or macOS.'],
    ] }, id: 'nfr', caption: 'Non-functional requirements' },

    { h2: '3.8 Project Schedule' },
    { p: 'The project was planned in ten overlapping phases over about sixteen weeks: problem study and use-case analysis (weeks 1–2), literature survey (2–4), dataset audit and cleaning (3–4), agronomy engine (4–6), model training and evaluation (6–8), Node.js inference and API (7–9), decision engine and scheduler (9–11), web dashboard and chatbot (10–13), testing and validation (13–14), and report, presentation and review (14–16).' },
  ],
};
