module.exports = {
  n: 4,
  title: 'PROJECT ANALYSIS & DESIGN',
  blocks: [
    { h2: '4.1 Introduction' },
    { p: 'This chapter presents the analysis and design of the Smart Moisture Advisor. The system is modelled with the Unified Modeling Language (UML) and with data-flow diagrams: the use-case diagram identifies the actors and the services they need; data-flow diagrams show how data moves from satellite observations to farmer advisories; the class diagram describes the main software abstractions; sequence diagrams describe the three most important interactions; the state diagram models the irrigation life-cycle of a plot; activity diagrams describe the training pipeline and the advisory logic; and component and deployment diagrams describe the software structure and its physical deployment. The chapter concludes with the layered system architecture, the data design and the user-interface design.' },

    { h2: '4.2 UML Diagrams' },
    { h3: '4.2.1 Use-case diagram' },
    { p: 'The use-case diagram in {fig:usecase} shows five actors. The **Farmer** views the plot advisory, chooses a language and listens to it, asks the Krishi Mitra chatbot and accepts or overrides advice. The **Field Supervisor** monitors the region dashboard and farm map, optimises pump schedules and records overrides. The **Agronomist** sets weather scenarios, runs what-if simulations and reviews model explanations. The **Factory / Cane Department** uses the dashboard and pump schedules for planning, and the **Data Scientist / Administrator** updates the dataset and retrains the models. The central use case *Generate predictions* is included by every use case that needs model output, which reflects the design decision that all views are driven by the same seven models and are therefore mutually consistent.' },
    { fig: 'uml_usecase.png', id: 'usecase', caption: 'Use-case diagram of SMA', width: 4.9, maxH: 6.9 },
    { p: 'The main use cases are described in {tab:ucdesc}.' },
    { table: { headers: ['Use case', 'Actor(s)', 'Description', 'Outcome'], widths: [20, 16, 40, 24], size: 11, rows: [
      ['View plot advisory', 'Farmer', 'Enter a plot ID; the system predicts irrigation date, duration, stress, yield, loss from delay, fertigation and risk under the current scenario.', 'Advisory card, charts and plain-language text'],
      ['Choose language / read aloud', 'Farmer', 'Switch between English, Kannada, Hindi and Marathi; speech synthesis reads the advice.', 'Localised advice'],
      ['Ask Krishi Mitra', 'Farmer', 'Type a question in any supported language with a plot ID; language and intent are detected.', 'Answer consistent with the dashboard'],
      ['Accept / override advice', 'Farmer, Supervisor, Agronomist', 'Record whether advice was followed, the actual irrigation day and a reason.', 'Entry in feedback log for retraining'],
      ['View region dashboard', 'Supervisor, Factory', 'KPIs, 14-day irrigation calendar, stress and risk distribution, taluk tables, priority plots.', 'Region-level situational awareness'],
      ['Set weather scenario', 'Agronomist', 'Forecast rain, temperature and humidity anomaly, dry days since observation, method, pump flow.', 'All views recomputed'],
      ['Optimise pump schedule', 'Supervisor, Factory', 'Select area, power windows, feeder capacity and horizon.', 'WSPT timetable with KPIs vs rotation'],
      ['Run what-if simulation', 'Agronomist', 'Change any input with sliders and observe all predictions.', 'Live predictions and drivers'],
      ['Retrain ML models', 'Data Scientist', 'Run the training pipeline on new or real labelled data.', 'Updated models, metrics and fixtures'],
    ] }, id: 'ucdesc', caption: 'Description of the main use cases' },

    { h3: '4.2.2 Data-flow diagrams' },
    { p: 'The Level-0 data-flow diagram (context diagram) in {fig:dfd0} treats SMA as a single process. Satellite/GIS sources supply plot features, the weather scenario supplies forecast rain and anomalies, farmers supply plot IDs, questions and feedback, and supervisors supply power windows, feeder capacity and overrides. SMA returns plot advisories to farmers, dashboards and pump timetables to supervisors, and water-demand calendars and yield estimates to the sugar factory.' },
    { fig: 'uml_dfd0.png', id: 'dfd0', caption: 'Level-0 data-flow diagram (context diagram)', width: 5.8 },
    { p: 'The Level-1 data-flow diagram in {fig:dfd1} decomposes SMA into seven processes and three data stores. Raw plot records are ingested and cleaned (1.0) into the plot dataset D1. The training process (2.0) reads D1 and writes the trained models D2. The prediction process (3.0) combines features from D1, models from D2 and the weather scenario. Predictions flow into the decision engine (4.0), which feeds both the pump scheduler (5.0) and the advisory generator (6.0). User decisions are recorded (7.0) in the feedback log D3, which closes the learning loop by providing retraining data to process 2.0.' },
    { fig: 'uml_dfd1.png', id: 'dfd1', caption: 'Level-1 data-flow diagram', width: 3.0, maxH: 8.4 },

    { h3: '4.2.3 Class diagram' },
    { p: 'The class diagram in {fig:class} shows the main software abstractions. A **Farm** holds the observed features, polygon and data-quality flags of a plot, and a **Scenario** holds the weather and operating parameters. The **AdvisoryEngine** is the central class: it builds model features from a Farm and a Scenario, obtains predictions from the **ModelRegistry** (which aggregates seven **TreeEnsemble** objects), and creates an **Advisory** with the help of the **FertigationPlanner**, the **ExplainEngine** and the **I18n** component. The **PumpScheduler** and the **InsightsBuilder** consume advisory summaries, and the **ChatBot** reuses the AdvisoryEngine and I18n so that chatbot answers are identical to the dashboard.' },
    { fig: 'uml_class.png', id: 'class', caption: 'Class diagram', width: 6.0 },

    { h3: '4.2.4 Sequence diagrams' },
    { p: '{fig:seqadv} shows the sequence for the most frequent interaction — a farmer requesting a plot advisory in Kannada. The web UI calls the REST API, which validates and clamps the scenario and invokes the AdvisoryEngine. The engine applies the weather scenario, queries all seven models, computes the rain counterfactual, hydraulics, fertigation plan and 14-day projection, asks the ExplainEngine for feature effects and asks I18n to render the text. The optional fragment shows the farmer overriding the advice, which is stored through the feedback endpoint.' },
    { fig: 'uml_seq_advisory.png', id: 'seqadv', caption: 'Sequence diagram: plot advisory request', width: 6.0 },
    { p: '{fig:seqsch} shows how a supervisor obtains an optimised pump timetable. Summaries for the selected village are taken from the per-scenario cache; the scheduler builds the power slots, weights every plot by urgency and cane at risk, orders plots by the WSPT rule, packs them into feeder lanes and evaluates the plan against a first-come rotation.' },
    { fig: 'uml_seq_schedule.png', id: 'seqsch', caption: 'Sequence diagram: pump schedule optimisation', width: 5.8 },
    { h3: '4.2.5 State diagram' },
    { p: 'The state diagram in {fig:state} models the irrigation life-cycle of a plot. A plot is *Monitoring* while the root zone holds more than the readily available water. As the crop uses water it moves to *Due Soon* and then *Due Today/Tomorrow*. If forecast rain would refill the root zone, it enters *Rain Skip* and returns to monitoring once the rain arrives (or back to *Due* if the forecast fails). If irrigation is delayed beyond the readily available water, the plot becomes *Water Stressed*, which gives it high priority in the scheduler. Irrigation takes the plot to *Refilled* and then back to *Monitoring* until harvest.' },
    { fig: 'uml_state.png', id: 'state', caption: 'State diagram of a plot\'s irrigation status', width: 3.9, maxH: 5.8 },

    { h3: '4.2.6 Activity diagrams' },
    { p: 'The activity diagram in {fig:acttrain} describes the offline training pipeline: loading and cleaning data, generating seasonal scenarios, labelling them with the agronomy engine, adding noise, splitting by plot, training the four groups of models in parallel, evaluating against baselines, clustering management zones, exporting to JSON and verifying parity with the Node.js tests before serving.' },
    { fig: 'uml_activity_training.png', id: 'acttrain', caption: 'Activity diagram: model training pipeline', width: 4.2, maxH: 7.2 },
    { p: 'The activity diagram in {fig:actadv} describes the decision logic for one advisory, including soil depletion for dry days, the rain-skip rule, the irrigation status, hydraulics, fertigation, explanation and text generation.' },
    { fig: 'uml_activity_advisory.png', id: 'actadv', caption: 'Activity diagram: advisory generation', width: 4.2, maxH: 7.2 },

    { h3: '4.2.7 Component and deployment diagrams' },
    { p: 'The component diagram in {fig:component} shows the three parts of the system: the offline Python training package, the Node.js server (REST API, data loader, tree-ensemble inference, advisory engine, scheduler, explanation, insights, internationalisation and chatbot) and the browser single-page application that uses Chart.js and Leaflet. Trained models and metrics are the only artefacts passed from training to serving.' },
    { fig: 'uml_component.png', id: 'component', caption: 'Component diagram', width: 5.0 },
    { p: 'The deployment diagram in {fig:deploy} shows that the system needs only a user device with a browser and an application server with Node.js; the training workstation is used offline. Map tiles are fetched from public tile services, and integration with IMD forecasts, Sentinel-2 imagery and IoT gateways is planned.' },
    { fig: 'uml_deployment.png', id: 'deploy', caption: 'Deployment diagram', width: 5.0 },

    { h2: '4.3 System Architecture' },
    { p: 'SMA follows a layered architecture. The **data layer** consists of the plot dataset (CSV with GeoJSON polygons), the trained model files (JSON) and the feedback log (JSON Lines). The **intelligence layer** contains the tree-ensemble inference engine and the model registry. The **decision layer** contains the advisory engine, fertigation planner, explanation engine, pump scheduler and insights builder. The **service layer** is a stateless Express REST API that validates inputs and caches plot summaries per weather scenario. The **presentation layer** is a single-page web application with eight views. Because each layer depends only on the one below it, the ML models can be retrained, the data source replaced (for example by live STEPS records) or new front-ends (mobile app, SMS gateway, WhatsApp bot) added without changing the other layers.' },
    { p: 'Two architectural choices are worth highlighting. First, **training and serving are separated**: Python is used only offline, and the exported models are executed in JavaScript with a float32 comparison that reproduces scikit-learn exactly, so the deployed system has a single runtime. Second, **all views share one prediction path**: the dashboard, map, advisor, scheduler and chatbot all call the same advisory engine with the same scenario, so a farmer, a supervisor and the chatbot always see the same answer.' },

    { h2: '4.4 Data Design' },
    { p: 'The data dictionary of the input dataset is given in {tab:dict}. Each record is one geofenced plot sampled on the ESA WorldCover cropland class {cite:zanaga2021}.' },
    { table: { headers: ['Attribute', 'Type / unit', 'Description', 'Used as'], widths: [22, 18, 38, 22], size: 11, rows: [
      ['Farm_ID', 'Text', 'Anonymised plot identifier (e.g. MM-MD-0110)', 'Key'],
      ['District, Taluk, Village', 'Text', 'Administrative location (Mandya; 6 taluks; 10 villages)', 'Grouping, filters'],
      ['Farm_Area_ha', 'Number, ha', 'Plot area (constant 0.7355 ha)', 'Volume computation'],
      ['NDVI', 'Number, –', 'Normalized Difference Vegetation Index (6 missing values)', 'Model feature'],
      ['LAI', 'Number, m²/m²', 'Leaf Area Index', 'Model feature'],
      ['Soil_Moisture', 'Number, m³/m³', 'Volumetric soil moisture', 'Model feature'],
      ['Soil_pH', 'Number, –', 'Soil reaction', 'Model feature'],
      ['Organic_Carbon', 'Number, g/kg', 'Soil organic carbon', 'Model feature'],
      ['Rainfall_mm', 'Number, mm', 'Seasonal rainfall', 'Model feature'],
      ['Temperature_C', 'Number, °C', 'Mean air temperature', 'Model feature'],
      ['Relative_Humidity', 'Number, %', 'Mean relative humidity', 'Model feature'],
      ['Sampling_Method', 'Text', 'ESA_WorldCover_Cropland (constant)', 'Metadata'],
      ['.geo', 'GeoJSON', 'Plot boundary polygon', 'Map, centroid'],
    ] }, id: 'dict', caption: 'Data dictionary of the IrrigationAdvisoryDataset' },
    { p: 'In addition to the observed attributes, two derived inputs are used: the **crop age** in days after planting (not present in the dataset; a stable estimate per plot is used and can be overridden, while in production it comes from STEPS planting records) and the **forecast rain** for the next three days. Each exported model is stored as JSON containing the model type, the ordered feature list and, for every tree, parallel arrays of split features, thresholds, left and right child indices and leaf values; Gradient-Boosting models additionally store the initial prediction and the learning rate.' },

    { h2: '4.5 User Interface Design' },
    { p: 'The user interface serves two audiences — farmers who need one clear instruction, and supervisors and agronomists who need region-wide analysis — and follows these principles:' },
    { bullets: [
      '**One action first.** The advisor opens with a colour-coded banner ("Irrigate today", "Rain expected – skip irrigation") with pump hours and water volume.',
      '**Scenario-driven views.** Weather presets and sliders recompute every page for planning and demonstration.',
      '**Local language and voice.** Advice in English, Kannada, Hindi and Marathi, read aloud or copied as an SMS.',
      '**Accessible visuals.** Colour-blind-safe palette; stress and risk shown with icon and label, not colour alone; light and dark themes.',
      '**Transparency.** Probabilities, uncertainty, feature effects, accuracy and data-quality flags are visible.',
      '**Responsive layout.** Works on office monitors and field smartphones.',
    ] },
  ],
};
