module.exports = {
  n: 5,
  title: 'METHODOLOGY',
  blocks: [
    { h2: '5.1 Introduction' },
    { p: 'This chapter describes how SMA turns plot observations into recommendations: data analysis, pre-processing, physics-informed label generation, machine-learning models, the decision engine, pump scheduling and explanation, each with its algorithm steps and mathematical formulation.' },

    { h2: '5.2 System Block Diagram' },
    { p: 'The system block diagram in {fig:block} organises SMA into five layers. The **input layer** receives satellite indices, soil properties, seasonal climate, plot polygons, the weather scenario and the crop age. The **pre-processing layer** imputes missing values, flags anomalous readings and builds the model features, including soil-moisture depletion for dry days. The **machine-learning layer** holds seven supervised tree-ensemble models and one unsupervised clustering model, all executed natively in Node.js. The **decision-support engine** converts the predictions into a rain-adjusted irrigation status, water volume and pump hours, a fertigation plan, an optimised pump timetable and an explanation. The **output layer** delivers the results through the web dashboard and farm map, the plot advisory in four languages, the Krishi Mitra chatbot, the pump timetable and a REST API for integration with STEPS or a mobile application.' },
    { fig: 'uml_block.png', id: 'block', caption: 'System block diagram of SMA', width: 5.8 },

    { h2: '5.3 Dataset Description and Exploratory Analysis' },
    { p: 'The IrrigationAdvisoryDataset contains 1,000 geofenced sugarcane plots in Mandya district, Karnataka, distributed over six taluks and ten villages ({fig:map}). Each plot has an area of 0.7355 ha, giving a total of 736 ha. Summary statistics of the numerical features are listed in {tab:stats}.' },
    { fig: 'fig_dataset_map.png', id: 'map', caption: 'Location of the 1,000 plots, coloured by taluk', width: 5.2 },
    { table: { headers: ['Feature', 'Mean', 'Std. dev.', 'Min', 'Max', 'Missing'], widths: [30, 14, 14, 14, 14, 14], align: [0, 2, 2, 2, 2, 2], rows: [
      ['NDVI', '0.580', '0.089', '0.260', '0.787', '6'],
      ['LAI (m²/m²)', '0.602', '0.090', '0.400', '0.850', '0'],
      ['Soil moisture (m³/m³)', '0.223', '0.010', '0.218', '0.256', '0'],
      ['Soil pH', '6.37', '0.23', '6.00', '7.20', '0'],
      ['Organic carbon (g/kg)', '10.54', '1.85', '7.67', '20.00', '0'],
      ['Rainfall (mm)', '629.6', '74.6', '498.3', '711.3', '0'],
      ['Temperature (°C)', '23.25', '0.58', '22.20', '24.17', '0'],
      ['Relative humidity (%)', '78.88', '1.90', '76.20', '82.67', '0'],
    ] }, id: 'stats', caption: 'Descriptive statistics of the plot features' },
    { p: 'The feature distributions show that NDVI is approximately bell-shaped around 0.58, while soil moisture, temperature and humidity vary within narrow ranges because the satellite pass corresponds to a single, relatively moist season. Soil moisture ranges only from 0.218 to 0.256 m³/m³. The Pearson correlation matrix (also shown on the Model Insights page) reveals strong relationships between the climate variables: temperature is negatively correlated with humidity (r = −0.94) and rainfall (r = −0.85), and rainfall and humidity are positively correlated (r = 0.85). Such collinearity does not harm tree ensembles, but it matters for explanation, as discussed in Section 5.9.' },
    { p: 'Three conclusions shaped the methodology: (i) there are **no target labels**, so labels must be generated; (ii) the data cover one season, so **scenario augmentation** is needed to learn behaviour in dry, hot or rainy weather and at all crop ages; and (iii) area, district and sampling method are constant.' },

    { h2: '5.4 Data Pre-processing' },
    { p: '**Missing values.** Six NDVI values are missing, most likely because of cloud masking. Because neighbouring plots share climate and management, each missing value is imputed with the median NDVI of the plot\'s village, and the imputation is recorded as a data-quality flag.' },
    { p: '**Outlier detection.** Faulty or noisy sensor readings are a key operational challenge in the use case {cite:usecase}. SMA flags unusual values with the modified z-score of Iglewicz and Hoaglin {cite:iglewicz1993}, computed within each village so that a genuinely wetter village is not mistaken for a sensor error:' },
    { eq: 'z_{i} = (x_{i} − x̃) / (MAD / 0.6745),   flag if |z_{i}| > 3.5', id: 'mz' },
    { p: 'where x̃ is the village median and MAD is the median absolute deviation. When more than half of the values are identical (MAD = 0), the mean absolute deviation multiplied by 1.2533 is used as the scale. Flags are shown on the plot advisory so that field staff can verify the reading.' },
    { p: '**Constant columns** (Farm_Area_ha, District, Sampling_Method) are excluded from the model inputs; the plot area is still used to convert depths into volumes.' },
    { p: '**Scenario features.** At prediction time, the weather scenario modifies the observed features. The temperature anomaly ΔT_{a} is added to the temperature, humidity is reduced by 2.5 percentage points per degree of warming plus the humidity anomaly, and when *n* dry days have passed since the satellite observation the root zone is depleted with the predicted crop water use (FAO-56 water-balance bookkeeping):' },
    { eq: 'θ′ = max( PWP, θ − ET_{c} · n / (1000 · Z_{r}) )', id: 'deplete' },

    { h2: '5.5 Physics-Informed Label Generation' },
    { p: 'Because the dataset contains no irrigation or yield records, SMA follows the theory-guided data science paradigm {cite:karpatne2017}: established agronomic models are used to generate labels, and machine-learning models are trained on them. The agronomy engine implements the FAO-56 crop water balance {cite:allen1998} and the FAO-33 yield response {cite:doorenbos1979}.' },
    { h3: '5.5.1 Scenario augmentation' },
    { p: 'Each of the 1,000 plots is expanded into twelve seasonal scenarios, giving 12,000 training rows. The sampling distributions are listed in {tab:aug}. NDVI and LAI follow the expected sugarcane phenology curve scaled by the plot\'s observed vigour, so a plot that is greener than average remains greener in every scenario.' },
    { table: { headers: ['Variable', 'Scenario sampling'], widths: [30, 70], rows: [
      ['Crop age a', 'Uniform 0–365 days after planting'],
      ['Temperature T', 'Observed temperature + Uniform(−5, +13) °C'],
      ['Relative humidity RH', 'Observed RH − 2.5 × temperature anomaly + Normal(0, 5), clipped to 25–98%'],
      ['Soil moisture θ', '30%: observed + Normal(0, 0.015); 70%: Uniform(0.10, 0.38) m³/m³'],
      ['NDVI', 'Expected NDVI(a) × (observed NDVI / 0.58) + Normal(0, 0.04)'],
      ['LAI', 'Observed LAI × Expected NDVI(a) / 0.6 + Normal(0, 0.05)'],
      ['Forecast rain R', '55%: 0 mm; 45%: Exponential(mean 15 mm), capped at 80 mm'],
      ['Soil pH, organic carbon, rainfall', 'Observed value with small Gaussian perturbation'],
    ] }, id: 'aug', caption: 'Scenario augmentation parameters' },
    { h3: '5.5.2 Crop water requirement' },
    { p: 'Reference evapotranspiration is estimated with the Hargreaves–Samani equation {cite:hargreaves1985}, where R_{a} = 14.5 mm/day is the mean extraterrestrial radiation for latitude ≈ 12.5° N and the diurnal temperature range ΔT is estimated from humidity:' },
    { eq: 'ET_{0} = 0.0023 · R_{a} · (T + 17.8) · √ΔT ,   ΔT = clip(16 − 0.12·RH, 4, 14)', id: 'et0' },
    { p: 'The crop coefficient blends the FAO-56 stage curve for a twelve-month sugarcane crop ({tab:kc}) with an NDVI-based coefficient, so that a vigorous canopy transpires more:' },
    { eq: 'K_{c} = 0.6 · K_{c,stage}(a) + 0.4 · clip(1.5·NDVI + 0.05, 0.35, 1.30)', id: 'kc' },
    { eq: 'ET_{c} = K_{c} · ET_{0}', id: 'etc' },
    { table: { headers: ['Growth stage', 'Crop age (days)', 'K_{c,stage}', 'Stage sensitivity w'], widths: [30, 25, 20, 25], align: [0, 1, 1, 1], rows: [
      ['Germination', '0 – 45', '0.45', '0.8'],
      ['Tillering', '45 – 130', '0.45 → 1.25 (linear)', '1.2'],
      ['Grand growth', '130 – 290', '1.25', '1.5'],
      ['Maturity', '290 – 365', '1.25 → 0.75 (linear)', '0.5'],
    ] }, id: 'kc', caption: 'Sugarcane crop-coefficient curve and stage sensitivity' },
    { p: 'The resulting crop-coefficient curve and the expected NDVI and root-depth trajectories are plotted in {fig:kcfig}.' },
    { fig: 'fig_kc_ndvi.png', id: 'kcfig', caption: 'FAO-56 sugarcane crop coefficient, expected NDVI and root depth versus crop age', width: 6.0 },
    { h3: '5.5.3 Root-zone water balance and irrigation timing' },
    { p: 'Soil water-holding capacity increases with organic carbon (OC, g/kg), and the root depth grows from 0.3 m to 1.2 m during the first 150 days:' },
    { eq: 'FC = 0.27 + 0.003·OC ,   PWP = 0.12 + 0.0015·OC', id: 'soil' },
    { eq: 'Z_{r} = 0.3 + 0.9 · min(a, 150) / 150', id: 'zr' },
    { p: 'The total and readily available water and the current root-zone depletion D_{r} follow FAO-56, with the depletion fraction p adjusted for evaporative demand:' },
    { eq: 'TAW = 1000·(FC − PWP)·Z_{r} ,   D_{r} = clip(1000·(FC − θ)·Z_{r}, 0, TAW)', id: 'taw' },
    { eq: 'p = clip(0.65 + 0.04·(5 − ET_{c}), 0.4, 0.8) ,   RAW = p · TAW', id: 'raw' },
    { p: 'Irrigation is due when the depletion reaches RAW. Effective forecast rain P_{eff} delays that moment, giving the label for the number of days to irrigation and the net irrigation depth needed to refill the root zone:' },
    { eq: 'P_{eff} = 0.8 · max(0, R − 3) ,   t_{irr} = clip((RAW − D_{r} + P_{eff}) / ET_{c}, 0, 15)', id: 'tirr' },
    { eq: 'd_{net} = RAW if t_{irr} > 0, otherwise max(0, D_{r} − P_{eff})  (capped at 100 mm)', id: 'depth' },
    { p: 'The water balance is illustrated in {fig:wb}: without irrigation the depletion crosses RAW (stress begins) and approaches TAW (wilting); SMA recommends irrigation when RAW is reached, refilling the root zone to field capacity.' },
    { fig: 'fig_water_balance.png', id: 'wb', caption: 'Root-zone depletion with and without SMA-scheduled irrigation', width: 5.8 },
    { h3: '5.5.4 Water stress, yield, yield loss and disease risk' },
    { p: 'The FAO-56 water-stress coefficient K_{s} becomes less than one once depletion exceeds RAW. The water-stress score combines K_{s} with heat stress h, NDVI deficit n and closeness to the RAW threshold q, and is discretised into four classes (None < 0.10 ≤ Mild < 0.30 ≤ Moderate < 0.55 ≤ Severe):' },
    { eq: 'K_{s} = (TAW − D_{r}) / ((1 − p)·TAW) if D_{r} > RAW, else 1', id: 'ks' },
    { eq: 's = clip(0.7·(1 − K_{s}) + 0.15·h + 0.15·n + 0.15·q, 0, 1)', id: 'stress' },
    { p: 'where h = clip((T − 33)/7, 0, 1), n = clip((NDVI_{exp}(a) − NDVI)/0.3, 0, 1) and q = clip((D_{r}/RAW − 0.7)/0.3, 0, 1). Attainable yield (Y_{max} = 125 t/ha for the region) is reduced by multiplicative factors for soil pH, organic carbon, vigour, temperature, rainfall and current stress:' },
    { eq: 'Y = Y_{max} · g_{pH} · g_{OC} · g_{v} · g_{T} · g_{R} · (1 − 0.25·s)', id: 'yield' },
    { p: 'The yield loss caused by delaying irrigation by *d* days is obtained by simulating the daily depletion over the delay and integrating the FAO-33 relationship with the sugarcane yield-response factor K_{y} = 1.2, the stage sensitivity w from {tab:kc} and a heat multiplier η_{h}:' },
    { eq: '1 − Y_{a}/Y_{m} = K_{y} · (1 − ET_{a}/ET_{m})', id: 'fao33' },
    { eq: 'L(d) = 100 · K_{y} · [ Σ_{t=1..d} (1 − K_{s,t}) / 365 ] · w · 2 · η_{h}   (%)', id: 'loss' },
    { p: 'Disease risk takes the larger of a fungal score (humidity near a 27 °C optimum, wet soil, rain) and an early-shoot-borer score (hot, dry, young crop), discretised into Low, Medium and High. Every label receives field-realistic noise (e.g. ±0.6 days, ±5% ETc, ±4 t/ha yield) so that models learn patterns rather than memorising formulas.' },

    { h2: '5.6 Machine-Learning Models' },
    { p: 'Tree ensembles are used because they are the most accurate models for medium-sized tabular data {cite:grinsztajn2022}, capture thresholds such as the RAW limit, give feature importance and export as plain data. The ten inputs are NDVI, LAI, soil moisture, pH, organic carbon, temperature, humidity, seasonal rainfall, crop age and forecast rain (plus delay days for the yield-loss model).' },
    { p: '**Random Forest** {cite:breiman2001} averages *B* decision trees, each grown on a bootstrap sample with random feature subsets. For regression the prediction and its spread across trees, used by SMA as an uncertainty estimate, are:' },
    { eq: 'ŷ(x) = (1/B) Σ_{b=1..B} T_{b}(x) ,   σ(x) = √[ (1/B) Σ_{b} (T_{b}(x) − ŷ(x))² ]', id: 'rf' },
    { p: 'For classification, the class probabilities are the average of the leaf class proportions of all trees. **Gradient Boosting** {cite:friedman2001} builds an additive model in which each new tree h_{m} fits the negative gradient (the residuals for squared loss) of the current model, scaled by the learning rate ν:' },
    { eq: 'F_{M}(x) = F_{0} + ν · Σ_{m=1..M} h_{m}(x)', id: 'gbm' },
    { p: '**K-Means** {cite:macqueen1967} groups the standardised observed features of the 1,000 real plots into k = 4 management zones by minimising the within-cluster sum of squares:' },
    { eq: 'J = Σ_{k=1..K} Σ_{x_{i} ∈ C_{k}} ‖ x_{i} − μ_{k} ‖²', id: 'kmeans' },
    { p: 'The configuration of every model is given in {tab:hyper}. Hyperparameters were chosen to balance accuracy with the size of the exported JSON files.' },
    { table: { headers: ['Model', 'Target', 'Algorithm', 'Hyperparameters'], widths: [22, 24, 18, 36], size: 11, rows: [
      ['next_irrigation', 'Days to irrigation (0–15)', 'RF regressor', '40 trees, max depth 12, min samples per leaf 8'],
      ['water_requirement', 'ETc (mm/day)', 'GBM regressor', '200 trees, depth 4, learning rate 0.05'],
      ['irrigation_depth', 'Net depth (mm)', 'GBM regressor', '250 trees, depth 4, learning rate 0.05'],
      ['yield', 'Cane yield (t/ha)', 'GBM regressor', '250 trees, depth 4, learning rate 0.05'],
      ['yield_loss', 'Loss for a delay (%)', 'GBM regressor', '300 trees, depth 5, learning rate 0.05; 36,000 rows (3 delays per scenario)'],
      ['water_stress', '4 stress classes', 'RF classifier', '40 trees, max depth 12, min samples per leaf 5'],
      ['disease_risk', '3 risk classes', 'RF classifier', '30 trees, max depth 10, min samples per leaf 5'],
      ['zones', 'Management zone', 'K-Means', 'k = 4, 20 initialisations, standardised features'],
    ] }, id: 'hyper', caption: 'Model configuration and hyperparameters' },
    { h3: '5.6.1 Validation strategy and metrics' },
    { p: 'Because each plot contributes twelve scenarios, a random split would leak information from a plot into both training and test sets. SMA therefore uses a **group split by plot**: 80% of the plots (9,600 rows) are used for training and the remaining 20% (2,400 rows) are never seen during training. Each model is compared with a baseline (linear regression or logistic regression). Regression models are evaluated with the coefficient of determination and the mean absolute error, and classifiers with accuracy and the macro-averaged F1 score {cite:hastie2009}:' },
    { eq: 'R² = 1 − Σ(y_{i} − ŷ_{i})² / Σ(y_{i} − ȳ)² ,   MAE = (1/N) Σ |y_{i} − ŷ_{i}|', id: 'r2' },
    { eq: 'F1_{macro} = (1/C) Σ_{c} 2·P_{c}·R_{c} / (P_{c} + R_{c})', id: 'f1' },
    { h3: '5.6.2 Ordinal decision rule' },
    { p: 'For ordered classes (None < Mild < Moderate < Severe), reporting the class with the highest probability can understate risk: probabilities of 0.03, 0.45, 0.41 and 0.11 give *Mild* by arg-max although there is a 52% chance of moderate-or-worse stress. SMA therefore reports the **ordinal median** — the first class at which the cumulative probability reaches 50% — which is *Moderate* in this example and is safer for farmers:' },
    { eq: 'ĉ = min{ k : Σ_{j ≤ k} P(j) ≥ 0.5 }', id: 'ordinal' },

    { h2: '5.7 Decision-Support Engine' },
    { p: 'The decision engine turns model outputs into concrete actions. For each plot it performs the steps of Algorithm 5.1.' },
    { algo: 'Algorithm 5.1: Rain-adjusted plot advisory', steps: [
      'Build the feature vector from the plot and the weather scenario; deplete soil moisture for dry days using {eq:deplete}.',
      'Predict days to irrigation t (mean and spread), ETc, net depth, stress probabilities, yield, disease risk and loss for a 5-day delay.',
      'If forecast rain R > 0, predict t₀ with R = 0 (no-rain counterfactual).',
      'If R ≥ 5 mm, round(t₀) ≤ 2 and round(t) > round(t₀), set status = RAIN SKIP; otherwise set status = TODAY, TOMORROW or IN N DAYS from round(t).',
      'Compute gross depth, water volume and pump hours for the irrigation method and pump flow; for drip irrigation also compute the daily run-time.',
      'Compute the weekly water requirement and the saving against fixed-interval practice.',
      'Generate the fertigation plan for the crop stage, the 14-day moisture projection, the yield-loss curve for 0–14 days and the explanation.',
      'Render the advisory text in the requested language and return the result.',
    ] },
    { p: 'The irrigation hydraulics use the application efficiency η of the method (flood 0.55, furrow 0.65, sprinkler 0.75, drip 0.90), the plot area A in hectares and the pump flow Q in m³/h:' },
    { eq: 'd_{gross} = d_{net} / η ,   V = d_{gross} · A · 10 (m³) ,   H = V / Q (hours)', id: 'hyd' },
    { p: 'The water saving is measured against a conventional fixed schedule of 70 mm gross every 8 days, which is typical of farmer practice:' },
    { eq: 'W_{SMA} = max(0, 7·ET_{c} − P_{eff}) / η ,   W_{conv} = 70 × 7 / 8 ,   Saving = 1 − W_{SMA} / W_{conv}', id: 'saving' },
    { p: 'Energy saved is the pumping time avoided times the power of a 5 HP (3.73 kW) motor. The fertigation planner splits a 250:100:125 kg N:P₂O₅:K₂O per hectare package by stage ({tab:fert}), adjusts nitrogen for organic carbon (−10% above 7.5 g/kg, +25% below 5 g/kg), converts nutrients to 12-61-0, urea and muriate of potash, and adds notes on soil pH, vigour, stress and the no-nitrogen-after-eight-months rule.' },
    { table: { headers: ['Stage (days)', 'N share', 'P₂O₅ share', 'K₂O share'], widths: [40, 20, 20, 20], align: [0, 1, 1, 1], rows: [
      ['Germination (0–45)', '10%', '25%', '10%'],
      ['Tillering (45–130)', '40%', '45%', '30%'],
      ['Grand growth, early (130–240)', '50%', '30%', '45%'],
      ['Grand growth, late (240–290)', '0%', '0%', '15%'],
      ['Maturity (290+)', '0%', '0%', '0%'],
    ] }, id: 'fert', caption: 'Stage-wise fertigation split of the NPK package' },

    { h2: '5.8 Pump Scheduling Algorithm' },
    { p: 'Rural pump sets receive three-phase power only in fixed windows (about seven hours a day), and a feeder can run only a limited number of pumps at once. Each plot *j* that needs water within the horizon is a job with processing time p_{j} (pump hours) and weight w_{j}, derived from the cane at risk L_{j} predicted by the yield-loss model, the stress probability P_{j} and an urgency factor u_{j} (2 if due today, otherwise 1):' },
    { eq: 'w_{j} = u_{j} · (L_{j} + 0.5 · P_{j}) + 0.01 ,   objective: minimise Σ_{j} w_{j} · C_{j}', id: 'wspt' },
    { p: 'where C_{j} is the completion time of job *j*. For a single machine, Smith\'s rule {cite:smith1956} — processing jobs in decreasing order of w_{j}/p_{j} (Weighted Shortest Processing Time) — is optimal. For parallel feeder lanes with power windows, SMA uses WSPT list scheduling {cite:pinedo2016}, as given in Algorithm 5.2.' },
    { algo: 'Algorithm 5.2: WSPT pump scheduling under power windows', steps: [
      'Build the list of power slots for each day of the horizon from the configured windows (for example 06:00–10:00 and 17:00–20:00).',
      'Select plots due within the horizon (all plots for drip irrigation) that are not in rain-skip state; compute p_{j} and w_{j}.',
      'Sort jobs in decreasing order of w_{j} / p_{j}.',
      'For each job, choose the feeder lane that becomes free earliest; allocate minutes in the current power slot and continue in the next slot when power goes off, until the job is complete or the horizon ends.',
      'Repeat the packing with first-come-first-served (rotation) order as a baseline.',
      'Evaluate both plans: plots completed, cane at risk still pending, estimated cane loss, average finish time of high-stress plots, pump hours and energy.',
    ] },
    { p: 'Sorting dominates the running time, so the algorithm runs in O(n log n + n·s) for n jobs and s power slots — milliseconds for a village.' },

    { h2: '5.9 Explainability Method' },
    { p: 'For each prediction, SMA computes a local explanation by replacing one feature at a time with the regional median x̃_{f} and measuring the change in the prediction. A positive effect on days-to-irrigation means the feature delays irrigation compared with a typical plot:' },
    { eq: 'φ_{f}(x) = f(x) − f(x with x_{f} := x̃_{f})', id: 'explain' },
    { p: 'This model-agnostic sensitivity analysis is related to SHAP {cite:lundberg2017} but cheap enough for every request; the three largest effects become sentences such as "Soil moisture is lower than the regional median, which brings forward irrigation by 4.8 days."' },

    { h2: '5.10 Multilingual Advisory and Chatbot' },
    { p: 'Predictions are converted into template-based sentences in English, Kannada, Hindi and Marathi, which keeps every sentence auditable and consistent with the dashboard; the same structured output can later feed a large language model, as the use case suggests.' },
    { p: 'The Krishi Mitra chatbot reuses the same engine: it detects the language from the Unicode script, detects the intent from multilingual keywords, extracts the plot ID and returns the relevant advisory lines, so it never contradicts the dashboard (implementation details in Section 6.7).' },
  ],
};
