module.exports = {
  n: 6,
  title: 'IMPLEMENTATION DETAILS',
  blocks: [
    { h2: '6.1 Introduction' },
    { p: 'SMA is implemented as an offline Python pipeline (about 470 lines) that labels, trains, evaluates and exports the models, and a Node.js application (about 3,100 lines) that serves the REST API and a single-page web application. This chapter presents the user interface, project structure, training and inference, API, security, testing and deployment.' },

    { h2: '6.2 System Implementation' },
    { p: 'The web application has eight views reachable from a sidebar: Overview, Farm Map, Farm Advisor, What-If Simulator, Pump Scheduler, Model Insights, Krishi Mitra and About & Governance. A weather-scenario bar at the top of the operational views provides four presets and sliders for forecast rain, temperature and humidity anomalies, dry days since the satellite pass, irrigation method and pump flow. The screenshots below were captured with the *Summer dry spell* preset (seven dry days since the satellite observation and a temperature 8 °C above normal) unless stated otherwise.' },
    { fig: 'ss_overview.png', id: 'ssov', caption: 'Overview dashboard (summer dry spell scenario)', width: 6.0 },
    { p: '**Overview dashboard ({fig:ssov}).** Key indicators show the plots monitored (1,000 plots, 736 ha), plots to irrigate today and tomorrow (637 and 212), plots under moderate or severe stress (204), weekly water and pump energy saved against fixed eight-day irrigation, rain-adjusted skips, expected cane production and disease alerts. A 14-day irrigation calendar, stress and risk bars, taluk-wise water comparison, a *Priority plots* table (each row opens the plot advisory) and a taluk/village summary table follow.' },
    { p: '**Farm map ({fig:ssmapz}).** The Leaflet map shows every plot coloured by a selectable layer (irrigation due date, water stress, NDVI, soil moisture, management zone or disease risk) with a legend, a taluk filter and village labels that keep it readable offline. Zooming in draws the real plot polygons, and clicking a plot opens a side panel with its status, key numbers, data-quality flags and a link to the full advisory. The figure shows Maddur taluk coloured by water stress.' },
    { fig: 'ss_map_zoom.png', id: 'ssmapz', caption: 'Farm map filtered to Maddur taluk, coloured by water stress', width: 6.0 },
    { fig: 'ss_advisor_top.png', id: 'ssadv', caption: 'Farm Advisor: action banner, farmer advisory and probabilities for plot MM-MD-0110', width: 6.0 },
    { p: '**Farm Advisor ({fig:ssadv}).** A colour-coded action banner (red for *Irrigate today*, amber for soon, blue for *Rain expected – skip*) shows the plot, the target date with model uncertainty (±0.1 days), pump run-time (22.4 h), water volume (1,120 m³) and crop water requirement (5.47 mm/day). The *Farmer advisory* card gives six plain-language lines (irrigation, stress, cost of a five-day delay, yield, fertigation, disease) and a *Why?* sentence, with **Read aloud** and **Copy SMS** buttons. The probability card shows the full stress distribution (3%, 45%, 41%, 11%), for which the ordinal rule reports *Moderate* stress.' },
    { fig: 'ss_advisor_charts.png', id: 'ssadv2', caption: 'Farm Advisor: moisture projection, yield-loss curve, fertigation, explanation and feedback', width: 6.0 },
    { p: '**Advisor analytics ({fig:ssadv2}).** The lower part shows the 14-day root-zone projection with and without irrigation, the yield-loss curve for delays of 0–14 days, the weekly fertigation plan in nutrients and products, the *Why this advice?* feature effects (soil moisture brings irrigation forward by 4.8 days), the plot conditions with zone and crop stage, and the human-in-the-loop accept/override controls.' },
    { p: '**Multilingual advisory.** Selecting ಕನ್ನಡ, हिंदी or मराठी regenerates the advisory in that language with local date formats; an English translation remains available for verification (examples in {tab:langs}).' },
    { fig: 'ss_simulator.png', id: 'sssim', caption: 'What-If Simulator with the "Heat wave, dry soil" preset', width: 6.0 },
    { p: '**What-If Simulator ({fig:sssim}).** Sliders for all ten inputs, the irrigation method and the plot area, plus presets such as *Heat wave, dry soil* and *Heavy rain coming*, update the predictions almost instantly. In the heat-wave example the models predict irrigation today, 6.52 mm/day of crop water use, a 92% probability of severe stress and a 4.58% yield loss for a five-day delay, driven mainly by soil moisture.' },
    { fig: 'ss_scheduler.png', id: 'sssch', caption: 'Pump Scheduler for village Hosur with two power windows and 20 pumps per feeder', width: 6.0 },
    { p: '**Pump Scheduler ({fig:sssch}).** The supervisor chooses the area, two power windows, feeder capacity and horizon. KPI cards compare demand with capacity and show the cane loss avoided and high-stress plots served versus a first-come rotation; a Gantt chart shows each pump lane with hatched no-power periods and segments coloured by stress, and can be toggled between the SMA plan and the rotation.' },
    { fig: 'ss_insights_top.png', id: 'ssins', caption: 'Model Insights: pipeline, model accuracy cards, feature importance and predicted-versus-actual plot', width: 6.0 },
    { p: '**Model Insights ({fig:ssins}).** The pipeline, test metric and baseline of every model, feature importance, predicted-versus-actual plots or confusion matrices, feature correlations, management zones, NDVI distribution, data-quality statistics and the feedback acceptance rate make the AI transparent.' },
    { fig: 'ss_chat.png', id: 'sschat', caption: 'Krishi Mitra chatbot answering in English and Kannada', width: 6.0 },
    { p: '**Krishi Mitra ({fig:sschat}).** The chatbot answers questions in any of the four languages; the same question about plot MM-MD-0110 asked in English and in Kannada returns the plot summary and irrigation instruction in the language of the question. The **About & Governance** view maps the eleven required models to their implementation and lists the responsible-AI measures.' },

    { h2: '6.3 Project Structure and Modules' },
    { p: 'The code is organised into the modules in {tab:modules}; the client uses native ES modules without a build step.' },
    { table: { headers: ['Path', 'Module', 'Responsibility'], widths: [30, 22, 48], size: 11, rows: [
      ['ml/agronomy.py', 'Agronomy engine', 'FAO-56 / FAO-33 functions used to generate labels'],
      ['ml/train.py', 'Training pipeline', 'Augmentation, labelling, training, evaluation, export, fixtures'],
      ['models/*.json', 'Trained models', 'Seven tree ensembles, K-Means zones, metrics.json, test fixtures'],
      ['src/data/farms.js', 'Data loader', 'CSV parsing, NDVI imputation, outlier flags, polygons, crop age'],
      ['src/ml/treeEnsemble.js', 'Inference engine', 'RF / GBM tree walking with float32 parity, uncertainty'],
      ['src/ml/registry.js', 'Model registry', 'Loads models, assigns management zones'],
      ['src/engine/advisory.js', 'Advisory engine', 'Scenario features, predictions, rain rule, hydraulics, advisory'],
      ['src/engine/agronomy.js', 'Agronomy helpers', 'Water-balance projection, growth stage, fertigation planner'],
      ['src/engine/scheduler.js', 'Pump scheduler', 'Power slots, WSPT packing, rotation baseline, KPIs'],
      ['src/engine/explain.js', 'Explain engine', 'Median-substitution feature effects and reasons'],
      ['src/engine/insights.js', 'Insights builder', 'KPIs, calendar, taluk / village statistics, correlations'],
      ['src/engine/i18n.js, chat.js', 'Language layer', 'EN / KN / HI / MR templates, chatbot'],
      ['src/app.js, server.js', 'REST API', 'Routes, validation, caching, static hosting'],
      ['public/', 'Web application', 'HTML, CSS and eight page modules (Chart.js, Leaflet)'],
      ['test/', 'Test suite', 'Model parity, engine and API tests (node:test)'],
    ] }, id: 'modules', caption: 'Project modules' },

    { h2: '6.4 Training Pipeline Implementation' },
    { p: 'The training script loads the dataset with pandas, builds the scenario table, labels it with the agronomy engine and trains each model with scikit-learn {cite:pedregosa2011}. Every fitted tree is exported as five parallel arrays — split feature (−1 for a leaf), threshold, left child, right child and leaf value — which keeps the JSON compact and makes inference a simple loop. Thresholds are written with nine significant digits so that the float32 comparison used by scikit-learn is reproduced exactly.' },
    { p: 'The script also writes *metrics.json* (test scores, baselines, feature importance, confusion matrices and prediction samples) and *test_fixtures.json* (40 held-out rows with the Python predictions), which the Node.js tests use to verify that inference matches.' },

    { h2: '6.5 Tree-Ensemble Inference in Node.js' },
    { p: 'The inference engine walks each tree from the root to a leaf. scikit-learn casts inputs to 32-bit floats before comparing them with thresholds; the engine reproduces this with *Math.fround*, which is why the JavaScript predictions are identical to Python. Random-Forest regressors average the leaves (and return their standard deviation as uncertainty), Random-Forest classifiers average class-probability vectors, and Gradient-Boosting models add the scaled sum of the leaves to the initial value.' },
    { code: [
      'function leafValue(tree, x) {',
      '  let i = 0;',
      '  while (tree.f[i] !== -1) {',
      '    i = Math.fround(x[tree.f[i]]) <= tree.t[i] ? tree.l[i] : tree.r[i];',
      '  }',
      '  return tree.v[i];',
      '}',
      '// Gradient Boosting:  init + learningRate * sum of leaf values',
      '// Random Forest:      mean of leaf values (or of class-probability vectors)',
    ], caption: 'Listing 6.1: Tree traversal with float32 parity (src/ml/treeEnsemble.js)' },
    { p: 'Plot summaries for all 1,000 plots are computed once per weather scenario and cached (up to 30 scenarios), so switching pages is instantaneous. A full region summary takes about 0.2 s and a detailed single-plot advisory, including the 15-point yield-loss curve and the explanation, about 3 ms.' },

    { h2: '6.6 REST API' },
    { p: 'All functionality is exposed through a stateless JSON REST API ({tab:api}) that STEPS, a mobile app or an SMS gateway can reuse; inputs are validated (HTTP 400 for malformed input, 404 for unknown plots).' },
    { table: { headers: ['Method', 'Endpoint', 'Description'], widths: [12, 36, 52], size: 11, rows: [
      ['GET', '/api/health', 'Health check (plots and models loaded)'],
      ['GET', '/api/meta', 'Taluks and villages, languages, methods, defaults, bounds'],
      ['GET', '/api/farms?taluk=&village=', 'Summary advisory for every plot under a scenario'],
      ['GET', '/api/farms/geo', 'Plot polygons for the map'],
      ['GET', '/api/farms/:id?lang=kn&cropAge=', 'Full advisory for one plot in a language'],
      ['POST', '/api/predict', 'What-if prediction for arbitrary inputs'],
      ['GET', '/api/insights', 'Region KPIs, calendar, taluk / village tables, correlations, zones'],
      ['POST', '/api/schedule', 'Optimised pump schedule and rotation baseline'],
      ['GET', '/api/models', 'Model metrics, importance, confusion matrices, sizes'],
      ['POST / GET', '/api/feedback', 'Record and summarise accept / override decisions'],
      ['POST', '/api/chat', 'Krishi Mitra chatbot'],
    ] }, id: 'api', caption: 'REST API endpoints' },

    { h2: '6.7 Multilingual Advisory and Chatbot Implementation' },
    { p: 'The language layer stores one template per message type and language (for example *irrigate_today*, *rain_skip*, *stress*, *delay*, *yield*, *fert* and *fungal*), with placeholders such as {hours}, {volume} and {date}. The advisory engine fills the placeholders with model outputs and formats dates with the locale of the chosen language (en-IN, kn-IN, hi-IN, mr-IN), so that the same numbers appear in every language. {tab:langs} shows the first two lines of the advisory for plot MM-MD-0110 when 40 mm of rain is forecast during a dry spell. Kannada and Devanagari text is rendered with Unicode fonts, and the browser speech-synthesis API reads it aloud when a voice for the language is installed.' },
    { table: { headers: ['Language', 'Advisory text generated by SMA'], widths: [16, 84], size: 11, rows: [
      ['English', 'Rain is expected (40 mm in 3 days) - do not irrigate now. Next irrigation around Sun, 4 Oct. Water stress: Mild (49% chance of moderate or severe stress).'],
      ['Kannada', 'ಮಳೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ (3 ದಿನಗಳಲ್ಲಿ 40 ಮಿ.ಮೀ) - ಈಗ ನೀರು ಹಾಯಿಸಬೇಡಿ. ಮುಂದಿನ ನೀರಾವರಿ ಸುಮಾರು ಭಾನು, 4 ಅಕ್ಟೋ ರಂದು. ನೀರಿನ ಒತ್ತಡ: ಸ್ವಲ್ಪ (ಮಧ್ಯಮ ಅಥವಾ ತೀವ್ರ ಒತ್ತಡದ ಸಾಧ್ಯತೆ 49%).'],
      ['Hindi', 'बारिश की संभावना है (3 दिनों में 40 मिमी) - अभी सिंचाई न करें। अगली सिंचाई लगभग रवि, 4 अक्टू॰ को। जल तनाव: हल्का (मध्यम या गंभीर तनाव की संभावना 49%)।'],
      ['Marathi', 'पावसाची शक्यता आहे (3 दिवसांत 40 मिमी) - आत्ता पाणी देऊ नका. पुढील पाणी सुमारे रवि, ४ ऑक्टो रोजी. पाण्याचा ताण: सौम्य (मध्यम किंवा तीव्र ताणाची शक्यता 49%).'],
    ] }, id: 'langs', caption: 'The same advisory generated in four languages (plot MM-MD-0110, rain forecast)' },
    { p: 'The chatbot module implements language detection with Unicode ranges (U+0C80–U+0CFF for Kannada and U+0900–U+097F for Devanagari) and a short list of Marathi-specific words to separate Marathi from Hindi. Intent keywords are stored for all four languages (for example *water*, *पानी*, *ನೀರು* and *पाणी* for irrigation). Answers are filtered to the lines that match the detected intents, so that a question about fertiliser returns only the fertigation line. All translations are template-based and should be reviewed by native speakers before large-scale deployment.' },

    { h2: '6.8 Security and Privacy Implementation' },
    { p: 'The API validates every input: numeric scenario parameters are parsed and clamped to physical ranges (for example forecast rain 0–150 mm and pump flow 5–200 m³/h), irrigation methods are checked against an allow-list, time windows must match the HH:MM format, request bodies are limited to 100 kB and invalid values are rejected with HTTP 400. Security headers (X-Content-Type-Options, Referrer-Policy) are set and the framework signature header is disabled. All text inserted into the web page is HTML-escaped to prevent script injection. No secrets or credentials are stored in the code. Plots are identified only by anonymised IDs, and the feedback log stores only the plot ID, the user role, the decision, the recommended and actual days and an optional reason, in line with the data-minimisation principle of the DPDP Act, 2023 {cite:dpdp2023}.' },

    { h2: '6.9 Testing' },
    { p: 'The system is verified by 23 automated tests written with the built-in Node.js test runner and grouped into three suites ({tab:tests}). All tests pass. The model-parity tests are particularly important: they prove that the models served in production behave exactly like the models evaluated in Python, so the accuracy reported in Chapter 7 applies to the deployed system. Every page was also exercised in a headless Chromium browser for each weather scenario, with no browser errors reported.' },
    { table: { headers: ['Suite', 'Test case', 'Expected result', 'Status'], widths: [15, 42, 31, 12], size: 11, rows: [
      ['Model parity', 'Next irrigation, water requirement, depth and yield predictions on 40 held-out rows', '|JS − Python| < 10⁻⁴', 'Pass'],
      ['Model parity', 'Water-stress and disease-risk class probabilities', 'Match Python; sum to 1', 'Pass'],
      ['Model parity', 'Yield-loss predictions and feature order', 'Match Python', 'Pass'],
      ['Engine', 'Dataset loads 1,000 plots with polygons; 6 NDVI values imputed', 'No missing values', 'Pass'],
      ['Engine', 'Scenario parsing clamps unsafe input (rain 9999 mm, text, negative flow)', 'Values clamped to safe range', 'Pass'],
      ['Engine', 'Dry spell brings irrigation forward and raises stress', 'Fewer days, higher stress', 'Pass'],
      ['Engine', 'Forecast rain postpones a due irrigation', 'Status = rain_skip', 'Pass'],
      ['Engine', 'Drip needs less water than flood for the same plot', 'Lower weekly volume', 'Pass'],
      ['Engine', 'Yield-loss curve never decreases with longer delays', 'Monotonic curve', 'Pass'],
      ['Engine', 'Advisories generated in four languages', 'Four distinct texts, Kannada script present', 'Pass'],
      ['Engine', 'Scheduler respects power windows and feeder capacity; WSPT loss ≤ rotation', 'Constraints hold', 'Pass'],
      ['Engine', 'Chatbot language and intent detection; fertigation stops N late', 'Correct language / intent', 'Pass'],
      ['API', '/health, /farms, /farms/:id (404 for unknown), /predict (400 for invalid)', 'Correct status codes and payloads', 'Pass'],
      ['API', '/insights, /models, /schedule, /chat', 'Consistent totals, R² > 0.9', 'Pass'],
    ] }, id: 'tests', caption: 'Automated test cases' },

    { h2: '6.10 Deployment and Execution' },
    { p: 'The application requires only Node.js 18 or newer. After cloning the repository, *npm install* installs the four runtime dependencies (Express, csv-parse, Chart.js and Leaflet), *npm start* starts the server on port 3000 and *npm test* runs the 23 automated tests; the platform is then available at http://localhost:3000. Retraining on new data requires Python with *ml/requirements.txt* and *npm run train*, after which the tests confirm inference parity.' },
  ],
};
