module.exports = {
  n: 7,
  title: 'RESULT ANALYSIS',
  blocks: [
    { h2: '7.1 Introduction' },
    { p: 'Results are analysed at two levels: **model level**, on the 200 held-out plots (2,400 scenarios) against linear and logistic baselines, and **system level**, across four weather scenarios (irrigation decisions, water and energy, stress, irrigation method, rain-aware advice and pump scheduling), followed by a comparison with the literature. As labels come from FAO agronomy (Chapter 5), accuracy measures how well the models learn agronomic behaviour under realistic noise, and savings are estimates against a documented baseline practice.' },

    { h2: '7.2 Performance Measures' },
    { h3: '7.2.1 Regression models' },
    { p: 'The regression results are listed in {tab:reg} and plotted in {fig:r2}. All five regression models achieve a coefficient of determination between 0.89 and 0.98 on unseen plots and clearly outperform linear regression. The largest improvements are for irrigation depth (R² 0.975 versus 0.621) and yield loss (0.976 versus 0.499), whose relationships with the inputs are strongly non-linear because of the RAW threshold and the cap on refill depth. The next-irrigation model predicts the irrigation date with a mean absolute error of 0.69 days, compared with 2.58 days for linear regression — well within the one-day resolution at which irrigation is planned.' },
    { table: { headers: ['Model (target)', 'Algorithm', 'R²', 'MAE', 'Baseline R²', 'Baseline MAE'], widths: [30, 18, 11, 13, 14, 14], align: [0, 0, 1, 1, 1, 1], size: 11, rows: [
      ['Next irrigation (days)', 'Random Forest', '0.965', '0.69 d', '0.744', '2.58 d'],
      ['Crop water requirement (mm/day)', 'Gradient Boosting', '0.977', '0.17', '0.884', '0.40'],
      ['Irrigation depth (mm)', 'Gradient Boosting', '0.975', '1.75', '0.621', '6.67'],
      ['Cane yield (t/ha)', 'Gradient Boosting', '0.892', '3.36', '0.571', '6.81'],
      ['Yield loss from delay (%)', 'Gradient Boosting', '0.976', '0.36', '0.499', '2.14'],
    ] }, id: 'reg', caption: 'Performance of the regression models on unseen plots' },
    { fig: 'fig_r2.png', id: 'r2', caption: 'R² of the SMA models compared with linear-regression baselines', width: 5.8 },
    { p: 'The predicted-versus-actual plots in {fig:pa} show that predictions lie close to the diagonal across the full range. The spread for the next-irrigation model is largest near the 15-day cap, where exact timing matters least, and the yield model shows more scatter than the others because yield depends multiplicatively on six factors and carries the largest label noise (±4 t/ha).' },
    { fig: 'fig_pred_actual.png', id: 'pa', caption: 'Predicted versus actual values for four regression models (held-out plots)', width: 5.8 },

    { h3: '7.2.2 Classification models' },
    { p: 'The classification results are listed in {tab:cls} and the confusion matrices in {fig:cm}. The water-stress classifier reaches 87.8% accuracy and a macro-F1 of 0.82, and the disease-risk classifier 87.3% accuracy and a macro-F1 of 0.76, both clearly above logistic regression (macro-F1 0.75 and 0.51). The confusion matrices show that almost all errors occur between neighbouring classes (for example *Mild* predicted as *None*); no *Severe* stress case was predicted as *None* or *Mild*, which is the most important property for farmer safety.' },
    { table: { headers: ['Model', 'Classes', 'Accuracy', 'Macro-F1', 'Logistic acc.', 'Logistic F1'], widths: [22, 30, 12, 12, 12, 12], align: [0, 0, 1, 1, 1, 1], size: 11, rows: [
      ['Water stress (RF)', 'None, Mild, Moderate, Severe', '87.8%', '0.817', '83.5%', '0.754'],
      ['Disease & pest risk (RF)', 'Low, Medium, High', '87.3%', '0.763', '82.0%', '0.514'],
    ] }, id: 'cls', caption: 'Performance of the classification models on unseen plots' },
    { fig: 'fig_confusion.png', id: 'cm', caption: 'Confusion matrices of the water-stress and disease-risk classifiers', width: 5.9 },
    { p: 'Feature importances ({fig:imp}) are consistent with agronomy, which increases confidence that the models learned meaningful relationships. Soil moisture dominates the next-irrigation (85%) and water-stress (74%) models because it determines the current root-zone depletion; crop age dominates irrigation depth (96%) and ranks high in water requirement (47%) because it controls root depth and the crop coefficient; and yield depends on soil moisture, NDVI and crop age together.' },
    { fig: 'fig_importance.png', id: 'imp', caption: 'Top feature importances of three models', width: 6.0 },

    { h3: '7.2.3 System-level results across weather scenarios' },
    { p: 'The complete system was run for all 1,000 plots under four weather scenarios. The results are summarised in {tab:scen} and {fig:scen}.' },
    { table: { headers: ['Indicator', 'Satellite snapshot', 'Summer dry spell', 'Dry spell + 40 mm rain', 'Humid monsoon'], widths: [28, 18, 18, 18, 18], align: [0, 1, 1, 1, 1], size: 11, rows: [
      ['Plots to irrigate today / tomorrow', '0 / 0', '637 / 212', '0 / 0', '0 / 0'],
      ['Plots due within 7 days', '20', '955', '1', '0'],
      ['Moderate or severe water stress', '0', '204', '173', '0'],
      ['Rain-skip advisories', '0', '0', '894', '0'],
      ['Weekly water, SMA (m³)', '278,085', '387,174', '61,782', '125,898'],
      ['Weekly water saved vs fixed practice', '38.3%', '14.3%', '86.4%', '72.1%'],
      ['Rain used instead of pumping (m³)', '0', '0', '218,000', '100,000'],
      ['Pump energy saved per week (kWh)', '12,862', '4,798', '28,994', '24,215'],
      ['Cane at risk if delayed 5 days (t)', '36.3', '789.6', '299.0', '10.2'],
      ['Plots at medium disease risk', '0', '0', '0', '438'],
    ] }, id: 'scen', caption: 'System-level results for the 1,000 plots under four weather scenarios' },
    { fig: 'fig_scenarios.png', id: 'scen', caption: 'Advisory outcomes and weekly irrigation water under four weather scenarios', width: 6.0 },
    { p: 'Four observations follow. First, under the observed (moist) satellite conditions, SMA recommends 38.3% less water than the fixed practice of 70 mm every eight days, because soil storage is used before irrigating. Second, in a summer dry spell the advice changes sharply — 637 plots must be irrigated today and 204 are stressed — and SMA still uses 14.3% less water than fixed practice while directing it to the plots that need it. Third, when 40 mm of rain is forecast during that same dry spell, SMA postpones 894 irrigations, reducing weekly pumping from 387,174 m³ to 61,782 m³ and using about 218,000 m³ of rain instead. Fourth, in a humid monsoon spell, 438 plots are raised to medium disease risk, showing that the risk model reacts to humidity as intended. The 14-day irrigation calendar on the dashboard ({fig:ssov}) gives the sugar factory and the electricity utility a forecast of water and power demand for such periods.' },

    { h3: '7.2.4 Effect of irrigation method and taluk-level results' },
    { p: 'Because SMA converts net depth into gross water using the efficiency of the irrigation method, the platform can quantify the benefit of better irrigation technology ({fig:method}). Under the observed conditions, the recommended weekly water for all plots is 328,661 m³ with flood (27.1% less than fixed practice), 278,085 m³ with furrow (38.3%), 241,030 m³ with sprinkler (46.6%) and 200,866 m³ with drip irrigation (55.5%); the corresponding pump energy saved rises from 9,089 to 18,622 kWh per week.' },
    { fig: 'fig_methods.png', id: 'method', caption: 'Weekly water requirement by irrigation method', width: 5.4 },
    { p: 'At taluk level, all six taluks benefit from the plot-specific schedule. In the dry-spell scenario the share of stressed plots differs markedly — from 10.1% in Krishnarajpet to 36.6% in Pandavpura — showing why plot- and taluk-level advice is preferable to a single district-wide schedule.' },

    { h3: '7.2.5 Plot-level advisory, yield loss and pump scheduling' },
    { p: 'For plot MM-MD-0110 in the dry-spell scenario, the 14-day projection in {fig:loss}(a) shows that following SMA keeps the root zone above the stress threshold, whereas without irrigation the plant-available water falls below it. The yield-loss curve in {fig:loss}(b) quantifies the cost of waiting: about 0.8% if irrigated today, rising to 1.9% after six days and 6.7% after twelve days. This curve is what allows the scheduler to prioritise plots by the cane actually at risk.' },
    { fig: 'fig_loss_curve.png', id: 'loss', caption: 'Plot MM-MD-0110: (a) root-zone projection, (b) yield loss versus irrigation delay', width: 6.0 },
    { p: 'The pump scheduler was evaluated for village Hosur (93 plots needing water, 1,955 pump-hours of demand) with power from 06:00–10:00 and 17:00–20:00 over a three-day horizon ({tab:sched}). Demand greatly exceeds the feeder capacity, so the order of irrigation matters. With 20 pumps per feeder, the WSPT schedule reduces the estimated cane loss from 85.6 t to 80.2 t, serves 7 of the 14 high-stress plots instead of 2, and finishes high-stress plots 34 hours earlier on average, for the same pump-hours and energy. {fig:sched} shows that the optimised schedule is better than the rotation for every feeder capacity tested.' },
    { table: { headers: ['Metric (Hosur, 20 pumps, 3 days)', 'SMA (WSPT)', 'Rotation (FCFS)', 'Difference'], widths: [40, 20, 20, 20], align: [0, 1, 1, 1], size: 11, rows: [
      ['Estimated cane loss (t)', '80.23', '85.60', '−5.37'],
      ['Plots fully irrigated', '8', '5', '+3'],
      ['Cane at risk still waiting (t)', '72.61', '78.75', '−6.14'],
      ['High-stress plots served (of 14)', '7', '2', '+5'],
      ['High-stress plots: average finish (h)', '81.0', '115.1', '−34.1'],
      ['Pump-hours used / energy (kWh)', '420 / 1,567', '420 / 1,567', '0'],
    ] }, id: 'sched', caption: 'Pump-scheduling results for village Hosur' },
    { fig: 'fig_scheduler.png', id: 'sched', caption: 'Pump scheduling: (a) estimated cane loss and (b) high-stress plots served, for different feeder capacities', width: 6.0 },

    { h3: '7.2.6 Computational performance' },
    { p: 'Computational performance was measured on a four-core machine ({tab:perf}). Training all models takes about 75 seconds, the complete region (1,000 plots, seven models each) is scored in about 0.2 seconds, and a detailed advisory with explanation takes about 3 ms, so the system can easily serve the 18,000–25,000 farmers of the network from a single small server.' },
    { table: { headers: ['Operation', 'Measured time'], widths: [65, 35], align: [0, 1], rows: [
      ['Training and evaluating all models (12,000 scenarios + 36,000 loss rows)', '≈ 75 s'],
      ['Scoring all 1,000 plots under a new scenario (API call)', '≈ 0.19 s'],
      ['Detailed advisory for one plot (API call, incl. explanation)', '≈ 3 ms'],
      ['Total size of exported models (JSON)', '≈ 2.6 MB'],
      ['Automated test suite (23 tests)', '< 2 s'],
    ] }, id: 'perf', caption: 'Computational performance' },

    { h3: '7.2.7 Robustness across taluks, training size and uncertainty' },
    { p: 'To check that the models work equally well in every part of the district — a fairness requirement of the use case — the held-out plots were evaluated separately for each taluk ({tab:taluk}). The next-irrigation model achieves R² between 0.93 and 0.98 and an error between 0.59 and 0.93 days in all six taluks, and the water-stress accuracy ranges from 85.6% to 91.7%. Pandavpura has the largest error; it also has the highest share of stressed plots in the dry-spell scenario, and plots close to the stress threshold are where irrigation timing is most sensitive, which may explain the difference.' },
    { table: { headers: ['Taluk', 'Test plots', 'Next-irrigation R²', 'Next-irrigation MAE (days)', 'Water-stress accuracy'], widths: [24, 14, 20, 22, 20], align: [0, 1, 1, 1, 1], size: 11, rows: [
      ['Krishnarajpet', '48', '0.974', '0.59', '88.2%'],
      ['Maddur', '18', '0.972', '0.63', '85.6%'],
      ['Malavalli', '41', '0.972', '0.66', '88.2%'],
      ['Mandya', '33', '0.974', '0.65', '88.4%'],
      ['Pandavpura', '43', '0.934', '0.93', '86.0%'],
      ['Shrirangapattana', '17', '0.976', '0.65', '91.7%'],
    ] }, id: 'taluk', caption: 'Performance on held-out plots by taluk' },
    { p: 'The learning curve in {fig:lc} shows how the next-irrigation model improves as more plots are used for training. With only 40 plots the model already reaches R² 0.90; the error then falls steadily from 1.14 to 0.69 days at 800 plots, and the curve is still rising slowly. This indicates that the approach will benefit from the larger number of plots available in the GBL/KIAAR network and that a pilot with a few hundred field-labelled plots would be sufficient to recalibrate the models.' },
    { fig: 'fig_learning_curve.png', id: 'lc', caption: 'Learning curve of the next-irrigation model (held-out plots)', width: 5.4 },
    { p: 'Finally, the spread of the 40 Random-Forest trees was compared with the actual errors. The average spread is 0.75 days; 79% of predictions are within one day of the label, but only 43% of errors fall within one standard deviation of the tree spread and 77% within two. The spread is therefore a useful *relative* indicator of confidence (larger spread means less certain advice) but it is not a calibrated confidence interval; calibration with real field data is listed as future work.' },

    { h2: '7.3 Comparative Analysis' },
    { p: 'SMA was compared with representative systems from the literature survey ({tab:compare}). The comparison is qualitative because the systems were evaluated on different crops, data and metrics; where a capability is not described in a paper it is marked as *not reported*. SMA is the only one of the compared approaches that works from satellite data without in-field sensors or labelled history, combines irrigation timing with stress, yield loss, fertigation and pump scheduling, and delivers explained advice in local languages.' },
    { table: { headers: ['Capability', 'Goap et al. {cite:goap2018} (IoT + ML)', 'Kamienski et al. {cite:kamienski2019} (SWAMP)', 'Navarro-Hellín et al. {cite:navarro2016} (DSS)', 'FAO-56 scheduling {cite:allen1998}', 'SMA (this work)'], widths: [20, 16, 16, 16, 15, 17], size: 10, rows: [
      ['Primary data', 'Field sensors + weather forecast', 'IoT sensors, platform', 'Soil & climate sensors', 'Weather + crop + soil data', 'Satellite, soil, climate, scenario'],
      ['Needs in-field sensors', 'Yes', 'Yes', 'Yes', 'No', 'No (optional later)'],
      ['Needs labelled history', 'Sensor history', 'Not reported', 'Yes (expert decisions)', 'No', 'No (physics-informed labels)'],
      ['Irrigation timing / amount', 'Yes', 'Yes', 'Yes (weekly amount)', 'Yes', 'Yes, with ± uncertainty'],
      ['Rain-forecast adjustment', 'Yes', 'Not reported', 'Not reported', 'If forecast supplied', 'Yes, with water saved'],
      ['Stress probability / yield loss', 'No', 'No', 'No', 'Ks / Ky (deterministic)', 'Yes (probabilities, loss curve)'],
      ['Fertigation advice', 'No', 'No', 'No', 'No', 'Yes'],
      ['Pump scheduling under power limits', 'No', 'Not reported', 'No', 'No', 'Yes (WSPT)'],
      ['Explainability', 'Not reported', 'Not reported', 'Not reported', 'Transparent equations', 'Feature effects, probabilities'],
      ['Local-language advisory', 'Not reported', 'Not reported', 'Not reported', 'No', 'EN / KN / HI / MR, voice, chatbot'],
      ['Scale demonstrated', 'Single field', 'Pilot farms', 'Pilot plots', 'Any (manual)', '1,000 plots, 6 taluks'],
    ] }, id: 'compare', caption: 'Comparison of SMA with existing approaches from the literature' },
    { p: 'Quantitatively, SMA can be compared with two baselines available in this project: the conventional fixed-interval practice and the linear or logistic models ({tab:compare2}). Against fixed irrigation, SMA reduces weekly water by 38% under normal conditions (up to 56% with drip) and avoids pumping entirely for most plots when rain is forecast. Against linear models, the tree ensembles reduce the next-irrigation error from 2.58 to 0.69 days and raise macro-F1 for disease risk from 0.51 to 0.76. Against first-come pump rotation, WSPT scheduling serves more than three times as many high-stress plots within the horizon.' },
    { table: { headers: ['Comparison', 'Baseline', 'SMA', 'Improvement'], widths: [34, 22, 22, 22], align: [0, 1, 1, 1], size: 11, rows: [
      ['Weekly water (normal conditions, furrow)', '450,000 m³', '278,085 m³', '38.3% less'],
      ['Weekly water with 40 mm rain forecast (dry spell)', '450,000 m³', '61,782 m³', '86.4% less'],
      ['Next-irrigation error (MAE)', '2.58 days (linear)', '0.69 days', '73% lower'],
      ['Yield-loss model R²', '0.499 (linear)', '0.976', '+0.477'],
      ['Disease-risk macro-F1', '0.514 (logistic)', '0.763', '+0.249'],
      ['High-stress plots served (Hosur)', '2 of 14 (rotation)', '7 of 14', '3.5×'],
    ] }, id: 'compare2', caption: 'Quantitative comparison with baselines' },
  ],
};
